## Section Three - Boston Housing Data  
**Author: Zak Hussain**  
**Date: 10/18/2019 - 11/01/2019**  
**Course: ML 6140**

**Purpose**:   
Using the Boston data set, build a linear regressor that predicts NOX and another one that predicts median home values.

In [1]:
import pandas as pd

**Preprocessing**

In [2]:
# identified the column headers via looking at the data file. 
col_headers = ['crim', 'zn', 'indus',
           'chas', 'nox', 'rm',
           'age', 'dis', 'rad',
           'tax', 'ptratio', 'b', 
           'lstat', 'medv']

# I made the necessary changes to the boston.txt file and saved the necessary format to a new txt file, 'processed_boston.txt'
# create a dataframe from the new file. 
df = pd.read_csv('../Data/processed_boston.txt', delim_whitespace=True, names=col_headers)

In [3]:
# check to ensure the values in the dataframe are in-line with the 
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [4]:
# check the characteristices of the columns. 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
crim       506 non-null float64
zn         506 non-null float64
indus      506 non-null float64
chas       506 non-null int64
nox        506 non-null float64
rm         506 non-null float64
age        506 non-null float64
dis        506 non-null float64
rad        506 non-null int64
tax        506 non-null float64
ptratio    506 non-null float64
b          506 non-null float64
lstat      506 non-null float64
medv       506 non-null float64
dtypes: float64(12), int64(2)
memory usage: 55.4 KB

In [5]:
# check the characteristics of the data 
df.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677082,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [6]:
# standardize the data, as some columns have substantially different scales. 
from sklearn.preprocessing import StandardScaler

In [7]:
# create a StandardScaler object 
scaler = StandardScaler()

# fit and transform the orginal df, saving it to a standardized dataframe. 
standardized_df = pd.DataFrame(scaler.fit_transform(df), columns=col_headers)

In [8]:
# display the characteristics of the standardized data. 
standardized_df.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
count,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02
mean,-8.337643e-17,3.306534e-16,2.804081e-16,-3.100287e-16,-8.071058e-16,-5.189086e-17,-2.650493e-16,8.293761e-17,1.514379e-15,-9.934960e-16,4.493551e-16,-1.451408e-16,-1.595123e-16,-4.247810e-16
std,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00
min,-4.197819e-01,-4.877224e-01,-1.557842e+00,-2.725986e-01,-1.465882e+00,-3.880249e+00,-2.335437e+00,-1.267069e+00,-9.828429e-01,-1.313990e+00,-2.707379e+00,-3.907193e+00,-1.531127e+00,-1.908226e+00
25%,-4.109696e-01,-4.877224e-01,-8.676906e-01,-2.725986e-01,-9.130288e-01,-5.686303e-01,-8.374480e-01,-8.056878e-01,-6.379618e-01,-7.675760e-01,-4.880391e-01,2.050715e-01,-7.994200e-01,-5.994557e-01
50%,-3.906665e-01,-4.877224e-01,-2.110985e-01,-2.725986e-01,-1.442174e-01,-1.084655e-01,3.173816e-01,-2.793234e-01,-5.230014e-01,-4.646726e-01,2.748590e-01,3.811865e-01,-1.812536e-01,-1.450593e-01
75%,7.396560e-03,4.877224e-02,1.015999e+00,-2.725986e-01,5.986790e-01,4.827678e-01,9.067981e-01,6.623709e-01,1.661245e+00,1.530926e+00,8.065758e-01,4.336510e-01,6.030188e-01,2.685231e-01
max,9.933931e+00,3.804234e+00,2.422565e+00,3.668398e+00,2.732346e+00,3.555044e+00,1.117494e+00,3.960518e+00,1.661245e+00,1.798194e+00,1.638828e+00,4.410519e-01,3.548771e+00,2.989460e+00

**NOX Prediction model**  
For predicting the NOX levels, I used X to contain the feature-space, and y contains the ground truths. The data is then split into X_train, X_test, y_train, y_test. I then us LassoCV as my linear model. This model performs iterative fitting along a regularization path. Since it is a cross-validation estimator, It uses cross-validation to select the best model.

In [9]:
from sklearn.model_selection import train_test_split

# identify the feature space and ground truth. 
X = standardized_df.loc[:, standardized_df.columns != 'nox']
y = standardized_df['nox'] 

# split the data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3)

In [10]:
# build cross-validation estimator.  
from sklearn.linear_model import LassoCV

# characterize the cv to use 5-fold cross validation. 
lasso_clf = LassoCV(cv=5)
lasso_clf.fit(X_train, y_train) 

# because this is a regression model, save the predictions to y_pred, to get the confusion matrix. 
y_pred = lasso_clf.predict(X_test)
print('Here is the accuracy of the model on Predicting NOX levels.')
lasso_clf.score(X_test, y_test)

Here is the accuracy of the model on Predicting NOX levels.

0.8174685292020016

**Median Home Value Prediction Model**  
For predicting the median home value, I also implementd a LassoCV model.

In [15]:
# adjust the feature space and the labels. 
X = standardized_df.loc[:, standardized_df.columns != 'medv'] 
y = standardized_df['medv'] 

# split the data. 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.4)

In [19]:
# build another cross-validation estimator. 
lasso_clf2 = LassoCV(cv=3) 
lasso_clf2.fit(X_train, y_train) 

# because this is a regression model, save the predictions to y_pred, to get the confusion matrix. 
y_pred = lasso_clf2.predict(X_test)

# show the accuracy.
print("Accuracy for predicting the median home value: ")
lasso_clf2.score(X_test, y_test)

Accuracy for predicting the median home value:

0.719903598725705